In [3]:
# map the keyboard's characters to its coordinates, what it has on its left, right, up, down
# it MUST have unique values and order matters


import pandas as pd

# c = character
# x = row index
# y = column index
# l = left 
# r = right
# u = up
# d = down




def map_keyboard(keyboard):
    result = []
    tot_cols = len(keyboard.columns)
    tot_rows = len(keyboard)
    
    for x, this_row in keyboard.iterrows():        
        for y in keyboard:
            c = this_row[y]
            if c == None:
                continue
            
            if y-1 < 0:
                l = None
                r = keyboard[y+1][x]
            elif y+1 >= tot_cols:
                l = keyboard[y-1][x]
                r = None
            elif y-1 >= 0 and y+1 < tot_cols:
                l = keyboard[y-1][x]
                r = keyboard[y+1][x]

            if x-1 < 0:
                u = None
                d = keyboard[y][x+1]
            elif x+1 >= tot_rows:
                u = keyboard[y][x-1]
                d = None
            elif x-1 >= 0 and x+1 < tot_rows:
                u = keyboard[y][x-1]
                d = keyboard[y][x+1]

            result.append([c, x, y, l, r, u, d])
    
    return pd.DataFrame(result, columns=['c', 'x', 'y', 'l', 'r', 'u', 'd'])



keyboard_list = [
    ['a', 'b', 'c', 'd'],
    ['e', 'f', 'g', 'h'],
    ['i', 'k', 'l', 'm'],
    ['n', 'o', 'p', 'q']
]

keyboard_map = map_keyboard(pd.DataFrame(keyboard_list))
keyboard_map

    c  x  y     l     r     u     d
0   a  0  0  None     b  None     e
1   b  0  1     a     c  None     f
2   c  0  2     b     d  None     g
3   d  0  3     c  None  None     h
4   e  1  0  None     f     a     i
5   f  1  1     e     g     b     k
6   g  1  2     f     h     c     l
7   h  1  3     g  None     d     m
8   i  2  0  None     k     e     n
9   k  2  1     i     l     f     o
10  l  2  2     k     m     g     p
11  m  2  3     l  None     h     q
12  n  3  0  None     o     i  None
13  o  3  1     n     p     k  None
14  p  3  2     o     q     l  None
15  q  3  3     p  None     m  None

In [ ]:
def update_keyboard():